### ISSUE TITLE
What about the hybrid rosbuild stuff for the diff drive controller?

### ISSUE THREAD

**Issue by po1** [pal-robotics-forks/ros_controllers#10]
`ros_controllers` is backwards-compatible with fuerte via a shell script that will enable the manifests. They do not actively maintain a separate fuerte-devel branch, and expect the current hydro-devel branch to be usable as is in fuerte.
1. who is actually relying on this?
2. should we do the same for the newer diff drive controller?
3. if not, shouldn't we clean the other hydro-devel branches and separate them back?

@bmagyar @adolfo-rt @efernandez

**Comment by adolfo-rt** [comment]
I suggest doing the official cleanup that drops Fuerte support for the Indigo release. We could release the diffdrive upstream as Catkin-only.

**Comment by po1** [comment]
What does this imply for the diff drive controller? Can we leave it like this (separate branches, no hybrid build files)?

**Comment by adolfo-rt** [comment]
I say yes. It should have a hybrid build system if there's someone behind maintaining it. Otherwise it'll be broken.

**Comment by po1** [comment]
Okay, works for me.
